kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
#  image: kindest/node:v1.18
  extraPortMappings:
  - containerPort: 30100
    hostPort: 30070 # localhost:30070 to connect to the service
                    # https://medium.com/@talhakhalid101/creating-a-kubernetes-cluster-for-development-with-kind-189df2cb0792
                    # https://www.youtube.com/watch?v=s_o8dwzRlu4&t=2483s
- role: worker
- role: worker
- role: worker

