kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
#  - containerPort: 30080
  - containerPort: 30100
    hostPort: 30070		# localhost:30070
- role: worker
- role: worker
- role: worker

