- name: "Basic: Template keepalive to /usr/bin"
  ansible.builtin.template:
    src: ./files/keepalive
    dest: /usr/bin
    mode: 0777

- name: "Basic: apt-get update"
  ansible.builtin.apt:
    update_cache: yes

- name: "Basic: Install tree"
  apt:
    name: tree
    state: present

- name: "Basic: Install build-essential"
  apt:
    name: build-essential
    state: present

- name: "Basic: Install net-tools"
  apt:
    name: net-tools

- name: "Basic: Install ca-certificates"
  package:
    name: ca-certificates
    state: present

