- name: "Golang: Remove older installation"
  ansible.builtin.file:
    path: /usr/bin/go
    state: absent

- name: "Golang: Unarchive"
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go1.21.5.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

#- name: "Golang: Test PATH"
#  shell: "grep -c /usr/local/go/bin /etc/environment"
#  ignore_errors: yes
#  changed_when: False
#  register: fnd

- name: "Golang: Test PATH"
  lineinfile:
    path: /etc/environment
    regexp: /usr/local/go/bin
    line: "dummy-needless"
  register: found
  check_mode: yes
  changed_when: False

- name: "Golang: set PATH"
  ansible.builtin.replace:
    path: /etc/environment
    regexp: '^PATH=\"(.*)'
    replace: 'PATH="/usr/local/go/bin:\1'
  when: found.msg == "line added" # "line added" means that /usr/local/go/bin is not in PATH.
#  when: fnd.stdout == "0"

