- name: "Kafka: Fetch and unarchive"
  ansible.builtin.unarchive:
    src: https://dlcdn.apache.org/kafka/3.6.1/kafka_2.13-3.6.1.tgz
    dest: /usr/local
    remote_src: yes

- name: "Kafka: Test PATH"
  lineinfile:
    path: /etc/environment
    regexp: /usr/local/kafka_2.13-3.6.1/bin
    line: "dummy-needless"
  register: found
  check_mode: yes
  changed_when: False

- name: "Kafka: Set PATH"
  ansible.builtin.replace:
    path: /etc/environment
    regexp: '^PATH=\"(.*)'
    replace: 'PATH="/usr/local/kafka_2.13-3.6.1/bin:\1'
  when: found.msg == "line added" # "line added" means that /usr/local/kafka_2.13-3.6.1/bin is not in PATH.

- name: "Kafka: Set KAFKAPATH"
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: KAFKAPATH="/usr/local/kafka_2.13-3.6.1"

- name: "Kafka: Set CONFIG PATH"
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: KCF="/usr/local/kafka_2.13-3.6.1/config"
