---
- name: Install tools and apps
  become: True
  hosts: all
  tasks:
  - name: Basic tools
    include_tasks: basic.yaml
  - name: Remote Desctop GUI
    include_tasks: remotegui.yaml
  - name: Chrome
    include_tasks: chrome.yaml
  - name: VSCode
    include_tasks: vscode.yaml
  - name: nodejs
    include_tasks: nodejs.yaml
  - name: git
    include_tasks: git.yaml

  handlers:
  - name: Restart xrdp
    systemd:
      name: xrdp
      state: restarted
