---
- name: Install tools and apps
  become: True
  hosts: all
  tasks:
  - name: Basic tools
    include_tasks: basic.yaml
  - name: golang
    include_tasks: golang.yaml
  - name: Remote Desctop GUI
    include_tasks: remotegui.yaml
  - name: Chrome
    include_tasks: chrome.yaml
  - name: VSCode
    include_tasks: vscode.yaml
  - name: git
    include_tasks: git.yaml
  - name: Terraform
    include_tasks: terraform.yaml
  - name: Docker
    include_tasks: docker.yaml
  - name: Kind
    include_tasks: kind.yaml
  - name: Kubernetes
    include_tasks: kubernetes.yaml
  - name: k9s
    include_tasks: k9s.yaml
  - name: nodejs
    include_tasks: nodejs.yaml

  handlers:
  - name: Restart xrdp
    systemd:
      name: xrdp
      state: restarted
