    - name: "VSCode: Add Apt signing key"
      ansible.builtin.apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present

    - name: "VSCode: Add repository into sources list"
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode

    - name: "VSCode: Install"
      ansible.builtin.apt:
        name: "code"
        state: latest
        update_cache: true

